# Generated by Django 3.1.7 on 2021-04-09 10:41

from django.db import migrations, models
import eshopapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0002_auto_20210406_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price_list',
            field=models.FileField(blank=True, null=True, upload_to=eshopapi.models.Shop.user_directory_path),
        ),
    ]
