# Generated by Django 3.1.7 on 2021-04-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0003_auto_20210409_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Flag - whether the user is an administrator.', verbose_name='admin'),
        ),
    ]
