# Generated by Django 3.1.7 on 2021-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0005_auto_20210413_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id категории'),
        ),
    ]
