# Generated by Django 3.1.7 on 2021-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0006_auto_20210602_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id категории'),
        ),
    ]
