# Generated by Django 3.1.7 on 2021-06-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0007_auto_20210604_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='product_info',
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-name',), 'verbose_name': 'Параметр', 'verbose_name_plural': 'Список параметров'},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='measure_type',
        ),
        migrations.AddField(
            model_name='parameter',
            name='product_info',
            field=models.ForeignKey(blank=True, default=2222, on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='eshopapi.productinfo', verbose_name='Информация о продукте'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(default=2222, max_length=100, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Параметр'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('product_info', 'name'), name='unique_product_parameter'),
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
    ]
