# Generated by Django 3.1.7 on 2021-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0008_auto_20210606_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарезервировано'),
        ),
    ]
