# Generated by Django 3.1.7 on 2021-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0009_auto_20210607_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.PositiveIntegerField(default=222, verbose_name='id категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
