# Generated by Django 3.1.7 on 2021-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0010_auto_20210607_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='products_in_shop', to='eshopapi.Shop', verbose_name='Магазины'),
        ),
    ]
