# Generated by Django 3.1.7 on 2021-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0012_auto_20210614_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('basket', 'Статус корзины'), ('new', 'Новый'), ('send', 'Отправлен'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=15, verbose_name='Статус'),
        ),
    ]
