# Generated by Django 3.1.7 on 2021-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapi', '0013_auto_20210708_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='body_order',
            field=models.TextField(blank=True, null=True, verbose_name='Текст письма с заказом'),
        ),
    ]
